AB#627: Add enclave.json as payload to the executable
edgelesssys/ego pull request #27
Opened 2021-02-23 16:05 UTC by Nirusu

This is still missing the required bits in Edgeless RT to be handled from within the application, however guess this can be reviewed by looking at the outside from it.

The test is a bit tedious and long, but I wanted it to be a bit more explicit so we do not break any binaries.

2021-03-01 16:04 UTC, thomasten requested changes

2021-03-02 09:00 UTC, Nirusu commented on internal/cli/sign_test.go
> +	err = fs.WriteFile("helloworld_unsigned", copyBuffer, 0644)
They can be the same, that was just for a conceptual distinction between the two.

2021-03-02 09:48 UTC, Nirusu commented on internal/cli/sign.go
> +	if payloadSize > 0 {
Added those checks:

```golang
// Check if payload is at expected location
expectedPayloadSize := fileStat.Size() - int64(payloadSize)
if expectedPayloadSize != payloadOffset {
	return errors.New("expected payload location does not match real payload corruption, cannot safely truncate old payload")
}
```

```golang
else if (payloadSize == 0) != (payloadOffset == 0) {
	return errors.New("payload information in header is inconsistent, cannot continue")
}
```

Do you think they are sufficient?

2021-03-02 14:17 UTC, thomasten requested changes

2021-03-02 14:17 UTC, thomasten commented on internal/cli/sign_test.go
> +	require.EqualValues(oeInfoPayloadSizeUint64, n)
```suggestion
	// Reconstruct the JSON and check equality
	reconstructedJSON := make([]byte, payloadSize)
	n, err := signedExeMemfs.ReadAt(reconstructedJSON, payloadOffset)
	require.NoError(err)
	require.EqualValues(payloadSize, n)
```

2021-03-02 14:17 UTC, thomasten commented on internal/cli/sign_test.go
> +	require.NoError(err)
```suggestion
	require.NoError(err)
	defer signedExeMemfs.Close()
```
instead of cleanup at the end

2021-03-02 14:18 UTC, thomasten commented on internal/cli/sign_test.go
> +	err = fs.WriteFile("helloworld_unsigned", copyBuffer, 0644)
pls use a const for all occurrences of "helloworld"

2021-03-02 18:28 UTC, thomasten approved these changes

2021-03-02 18:28 UTC, merged