AB#675: add parsing of external errors
edgelesssys/ego pull request #42
Opened 2021-03-22 13:38 UTC by katexochen

Right now, the output of `go run ...` is out of order due to the buffering of output through external tools. This can be fixed by using `stdbuf -o0 ego run ... `

- [ ] Persistent deactivation of buffering need to be integrated before merging this PR.

2021-03-22 14:02 UTC, Nirusu commented
Oh yes, this is definitely needed.

Can I suggest also adding "Failed to open Intel SGX device." as an error, which occurs e.g. if the system does not support SGX or the required module is missing?

For reference, the error looks like this:
```
[erthost] loading enclave ...
[get_driver_type /home/sgx/jenkins/linux-ubuntuServer-release-build-trunk-213/build_target/PROD/label/Builder-UbuntuSrv18/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
2021-03-22T14:47:34+0100.220426Z [(H)ERROR] tid(0x7ff30ccf1780) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/home/nils/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/sgxload.c:oe_sgx_create_enclave:397]
2021-03-22T14:47:34+0100.220442Z [(H)ERROR] tid(0x7ff30ccf1780) | :OE_PLATFORM_ERROR [/home/nils/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/create.c:oe_sgx_build_enclave:1022]
2021-03-22T14:47:34+0100.221745Z [(H)ERROR] tid(0x7ff30ccf1780) | :OE_PLATFORM_ERROR [/home/nils/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/create.c:oe_create_enclave:1249]
2021-03-22T14:47:34+0100.221801Z [(H)ERROR] tid(0x7ff30ccf1780) | oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [/home/nils/edgelessrt/src/tools/erthost/erthost.cpp:main:163]
```

2021-03-24 09:07 UTC, thomasten requested changes
I couldn't find any better than using stdbuf. Added it. The SGX device error is on stderr. I fixed that, too. Pls pull before making below changes. Pls also review my commit.

2021-03-24 09:07 UTC, thomasten commented on cmd/ego/main.go
> +					fmt.Println("ERROR: Binary could not be run by Open Enclave.")
```suggestion
					fmt.Println("ERROR: Binary could not be loaded.")
					fmt.Println("Possibly the binary was not build with 'ego-go build'?")
				case cli.ErrValidAttr0:
					fmt.Println("ERROR: Binary could not be loaded.")
```
I think we shouldn't mention OE here. It's actually ERT, but I think these internals are rather confusing than helpful.

2021-04-06 06:19 UTC, katexochen commented on internal/cli/cli.go
> +	cmd.Stderr = io.MultiWriter(os.Stderr, &stderr)
Using MultiWriter, messy error messages will still be printed to users console. With StdoutPipe, we can replace them completely.

2021-04-06 07:11 UTC, katexochen commented on cmd/ego/main.go
> +			fmt.Println("ERROR: The Open Enclave info section is missing in the binary.")
I think ".oeinfo" is nothing an user will understand. We should also be consistent with amount of information we give to the user. If we want to handle OE as an internal, we should neither use ".oeinfo" nor "OE info" but instead describe the function of the section (I am not sure what the function of this section is right now).

2021-04-06 08:44 UTC, thomasten approved these changes

2021-04-06 08:44 UTC, merged