AB#700: Expose in-memory filesystem by default
edgelesssys/ego pull request #49
Opened 2021-04-19 14:25 UTC by Nirusu

Prerequisite: #https://github.com/edgelesssys/edgelessrt/pull/36

I think it might be worth discussing if there are any scenarios where we should prevent the user from exposing sensitive data from the host filesystem. Right now, I allowed the user to remount '/' as any part of the host filesystem, though I am not sure if we actually want to keep this. 

I think this might be useful for debugging, and there could also be many potential scenarios where this is used safely, so how do we handle that? One idea I had was that we could maybe bind this to the 'Debug' flag in the configuration and disable root mounts for non-debuggable applications, but yeah, this does not stop anyone from still mounting something potentially unsafe at other locations...

@thomasten @m1ghtym0 Any ideas how to handle this case?

2021-04-19 15:01 UTC, m1ghtym0 commented
Are you thinking about scenarios where mounting something from the hostfs inside the enclave could be a problem for the enclave or for the host?
I don't see a problem for the host since the enclave does not escalate privilege.
The other way around is the responsibility of the enclave author. Writing sensible information to mounted files of the hostfs should be handled with care. But I don't see why EGo should limit this.

2021-04-19 15:10 UTC, Nirusu commented
Scenarios which might be dangerous for the enclave.

I think eventually it's the responsibility of the enclave author, but if there are any cases which just seem like an obvious bad idea, I think it might be worth catching them.

2021-04-20 08:09 UTC, thomasten requested changes

2021-04-20 08:15 UTC, Nirusu commented on src/enc.cpp
> +    // mount hostfs when running under marblerun
I think that would be better, yes.

2021-04-20 08:15 UTC, Nirusu commented on src/enc.cpp
> +    if (chdir(memfs_mount_path) != 0)
EDG_CWD as before, or do we change that to PWD now?

2021-04-20 08:30 UTC, thomasten commented on src/enc.cpp
> +    if (chdir(memfs_mount_path) != 0)
We should use PWD. EDG_CWD contains the actual CWD within the hostfs and is an internal detail. I think it's more natural if the user sets PWD within the manifest.

2021-04-20 14:18 UTC, thomasten requested changes

2021-04-20 14:18 UTC, thomasten commented on go.mod
> +	github.com/edgelesssys/marblerun v0.3.2-0.20210419145600-46982f4b888e
change to master

2021-04-20 14:18 UTC, thomasten commented on src/enc.cpp
>      }
```suggestion
```
We may omit this because the working dir is already / by default.

2021-04-20 14:18 UTC, thomasten commented on internal/premain/core/core.go
> +	}
```suggestion
	isMarble := os.Getenv(marblerunEnvVarFlag) == "1"
```

2021-04-20 14:18 UTC, thomasten commented on cmd/integration-test/enclave.json
> +            "value": "/data"
add this feature to the docs

2021-04-20 16:31 UTC, thomasten approved these changes

2021-04-21 08:50 UTC, merged